site_name: Matemàtiques 2n Batxillerat científic

pages:
- Home: 'index.md'
- Temes:
    - '1. Derivades': 'temes/derivades.md'
    - '2. Funcions contínues i derivables': 'temes/funcions.md'
    - '3. Aplicacions de la derivada': 'temes/aplicacionsderivades.md'
    - '4. Integrals indefinides': 'temes/integralsindefinides.md'
    - '5. Integrals definides': 'temes/integralsdefinides.md'
    - '6. Matrius i Determinants': 'temes/matrius.md'
    - '7. Sistemes d equacions': 'temes/sistemes.md'
    - '8. Vectors a l espai': 'temes/vectors.md'
    - '9. Equacions de rectes i plans': 'temes/equacionsrectesplans.md'
    - '10. Posició relativa de rectes i plans': 'temes/posicionsrectesplans.md'
    - '11. Distàncies i angles': 'temes/distanciesangles.md'


- Miscel.lània: misc/misc.md
- Llicència: sobre.md

theme: cinder



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
